name: Release Android APK and Desktop apps

on:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*'
      - 'v*.*.*-*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  android:
    name: Android (Gradle)
    runs-on: ubuntu-latest
    env:
      ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
      ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
      ANDROID_STORE_PASSWORD: ${{ secrets.ANDROID_STORE_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: 'gradle'
      - uses: android-actions/setup-android@v3
      - name: Ensure Gradle wrapper is executable
        run: chmod +x ./gradlew
      - name: Install Android SDK components
        run: |
          yes | sdkmanager --licenses
          yes | sdkmanager "platform-tools" "platforms;android-36" "build-tools;35.0.0"
      - name: Restore keystore (if provided)
        if: env.ANDROID_KEYSTORE_BASE64 != ''
        run: echo "$ANDROID_KEYSTORE_BASE64" | base64 -d > my-release-key.jks
      - name: Build release APK
        run: |
          echo "::group::Gradle version"; ./gradlew --version; echo "::endgroup::"
          export ANDROID_KEYSTORE_PATH=$GITHUB_WORKSPACE/my-release-key.jks
          export ANDROID_KEY_ALIAS=${ANDROID_KEY_ALIAS}
          export ANDROID_KEY_PASSWORD=${ANDROID_KEY_PASSWORD}
          export ANDROID_STORE_PASSWORD=${ANDROID_STORE_PASSWORD}
          export SKIP_RELEASE_SIGNING=false
          ./gradlew :app:assembleRelease :app:bundleRelease --stacktrace
      - name: Upload Android artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: |
            app/build/outputs/apk/release/*.apk
            app/build/outputs/bundle/release/*.aab

  desktop:
    name: Desktop (Nativefier)
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Nativefier
        shell: bash
        run: |
          npm i -g nativefier
          nativefier --version || true
          which nativefier || true
      - name: Build
        shell: bash
        run: |
          set -euxo pipefail
          APP_URL="https://${GITHUB_REPOSITORY_OWNER}.github.io/${GITHUB_REPOSITORY#*/}/"
          OUT_DIR="dist-desktop"
          mkdir -p "$OUT_DIR"
          nativefier "$APP_URL" \
            --name "GlobGram" \
            --internal-urls ".*" \
            --disable-dev-tools \
            --single-instance \
            --out "$OUT_DIR"
          echo "Built contents (dist-desktop):"
          find "$OUT_DIR" -maxdepth 3 -type f -print | sed 's/^/  /' || true
      - name: Archive desktop app
        shell: bash
        run: |
          set -euxo pipefail
          OUT_DIR="dist-desktop"
          APP_DIR=$(find "$OUT_DIR" -mindepth 1 -maxdepth 1 -type d -name 'GlobGram*' | head -n 1 || true)
          echo "Detected app dir: ${APP_DIR:-<none>}"
          mkdir -p release-desktop
          if [ -z "$APP_DIR" ]; then
            echo "No Nativefier output found to archive" >&2
            exit 1
          fi
          case "${{ runner.os }}" in
            Windows)
              powershell -NoProfile -Command "Compress-Archive -Path '${APP_DIR}/*' -DestinationPath 'release-desktop/GlobGram-windows.zip' -Force" ;;
            macOS)
              # Preserve macOS app bundle metadata when present
              if command -v ditto >/dev/null 2>&1; then
                ditto -c -k --sequesterRsrc --keepParent "$APP_DIR" "release-desktop/GlobGram-macos.zip"
              else
                zip -r "release-desktop/GlobGram-macos.zip" "$APP_DIR"
              fi ;;
            Linux)
              zip -r "release-desktop/GlobGram-linux.zip" "$APP_DIR" ;;
          esac
      - name: Upload Desktop artifact
        uses: actions/upload-artifact@v4
        with:
          name: desktop-${{ runner.os }}
          path: release-desktop/*.zip
          if-no-files-found: error

  publish:
    name: Publish Release assets
    runs-on: ubuntu-latest
    needs: [android, desktop]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: '*'
          merge-multiple: true
          path: release-assets
      - name: List gathered assets
        run: |
          echo "Assets in release-assets:" && ls -R release-assets || true
      - name: Create/Update GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release-assets/**
          fail_on_unmatched_files: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
